# Generated by Django 5.0.6 on 2026-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(help_text='Local identifier. Synthetic in the prototype.', max_length=32, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Synthetic name used only inside the individual layer.', max_length=120)),
                ('age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_months', models.PositiveSmallIntegerField(blank=True, help_text='Used for infants; the red-flag rule set treats <2 months specially.', null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Not stated')], default='U', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['patient_code'],
            },
        ),
    ]
