# Generated by Django 5.0.6 on 2026-09-13 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text='Legacy field: linked a patient record to its own login for the optional patient portal, which has been removed from the application. No code path sets this any more.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
