# Generated by Django 5.0.6 on 2026-09-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_linked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Height in centimetres, if recorded.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='house_location',
            field=models.CharField(blank=True, help_text="A local reference for finding the household (e.g. 'Near the temple', 'House 24') — never GPS coordinates or a formal postal address.", max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Weight in kilograms, if recorded.', null=True),
        ),
    ]
