# Generated by Django 5.0.6 on 2026-08-12 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNDER_INVESTIGATION', 'Under investigation'), ('MONITORING', 'Monitoring'), ('MORE_DATA_REQUESTED', 'More data requested'), ('COMPLETED', 'Completed')], default='UNDER_INVESTIGATION', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('COMMUNITY', 'Community'), ('INDIVIDUAL', 'Individual')], max_length=16)),
                ('verdict', models.CharField(choices=[('PASS', 'Pass'), ('DOWNGRADE', 'Downgrade'), ('BLOCK', 'Block')], max_length=16)),
                ('passed', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=48)),
                ('rules', models.JSONField(default=list)),
                ('reasons', models.JSONField(default=list)),
                ('engine_version', models.CharField(default='1.0.0', max_length=16)),
                ('week_label', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('stage', models.CharField(max_length=48)),
                ('agent_name', models.CharField(max_length=64)),
                ('agent_layer', models.CharField(blank=True, max_length=32)),
                ('week_label', models.CharField(blank=True, max_length=16)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='OK', max_length=24)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('used_llm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='core.village')),
            ],
            options={
                'ordering': ['run_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cluster', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('FEVER', 'Fever-related'), ('RESPIRATORY', 'Respiratory'), ('DIARRHOEAL', 'Diarrhoeal'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation'), ('OTHER', 'Other')], max_length=24)),
                ('week_label', models.CharField(max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Plain-language narrative. Screened for prohibited claims.')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='MODERATE', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('corroborating_source_count', models.PositiveSmallIntegerField(default=0)),
                ('cross_level_verdict', models.CharField(blank=True, max_length=32)),
                ('cross_level_statement', models.TextField(blank=True)),
                ('safety_verdict', models.CharField(choices=[('PASS', 'Pass'), ('DOWNGRADE', 'Downgrade'), ('BLOCK', 'Block')], default='DOWNGRADE', max_length=16)),
                ('safety_status', models.CharField(blank=True, max_length=48)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('UNDER_INVESTIGATION', 'Under investigation'), ('CLOSED', 'Closed')], default='DETECTED', max_length=24)),
                ('orchestration_run_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('narrative_used_llm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='core.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('CHW', 'Community Health Worker reports'), ('PHC', 'PHC aggregate trends'), ('PHARMACY', 'Pharmacy category trends'), ('SCHOOL', 'School absenteeism'), ('WEATHER', 'Weather / environment'), ('LAB', 'Laboratory evidence'), ('RURALCARE_AGGREGATE', 'Aggregated RuralCare signal')], max_length=32)),
                ('source_name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('FEVER', 'Fever-related'), ('RESPIRATORY', 'Respiratory'), ('DIARRHOEAL', 'Diarrhoeal'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation'), ('OTHER', 'Other')], max_length=24)),
                ('village_code', models.CharField(max_length=32)),
                ('week_label', models.CharField(max_length=16)),
                ('baseline', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('data_quality', models.CharField(choices=[('GOOD', 'Good'), ('PARTIAL', 'Partial'), ('POOR', 'Poor'), ('MISSING', 'Not submitted')], default='GOOD', max_length=16)),
                ('status', models.CharField(choices=[('ANOMALY_DETECTED', 'Anomaly detected'), ('NORMAL', 'Within expected range'), ('SUPPORTING_CONTEXT', 'Supporting context'), ('CORROBORATING', 'Corroborating evidence'), ('INSUFFICIENT_DATA', 'Insufficient data'), ('NOT_REPORTED', 'Not reported (never treated as zero)')], max_length=24)),
                ('is_corroborating', models.BooleanField(default=False, help_text='Counts toward the two-independent-source rule. Weather does not.')),
                ('explanation', models.TextField(blank=True)),
                ('produced_by_agent', models.CharField(blank=True, max_length=64)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='alerts.alert')),
            ],
            options={
                'ordering': ['source_kind'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('VALID_SIGNAL', 'Valid signal'), ('FALSE_ALERT', 'False alert'), ('RESOLVED', 'Resolved')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('resolution_latency_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='alerts.alert')),
            ],
        ),
    ]
