# Generated by Django 5.0.6 on 2026-08-12 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('assessments', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetycheck',
            name='alert',
            field=models.ForeignKey(blank=True, help_text='Null when the hypothesis was BLOCKed and no alert was raised.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='safetycheck',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='assessments.patientassessment'),
        ),
        migrations.AddField(
            model_name='safetycheck',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.village'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx'),
        ),
    ]
