# Generated by Django 5.0.6 on 2026-09-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alert_category_alter_alertevidence_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevidence',
            name='operational_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='alertevidence',
            name='status',
            field=models.CharField(choices=[('ANOMALY_DETECTED', 'Anomaly detected'), ('NORMAL', 'Within expected range'), ('SUPPORTING_CONTEXT', 'Supporting context'), ('CORROBORATING', 'Corroborating evidence'), ('INSUFFICIENT_DATA', 'Insufficient data'), ('NOT_REPORTED', 'Not reported (never treated as zero)'), ('EXPECTED_UNAVAILABLE', 'Expected unavailable'), ('EXPECTED_VARIATION', 'Expected unusual activity')], max_length=24),
        ),
    ]
