# Generated by Django 5.0.6 on 2026-09-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('organization', models.CharField(help_text='Who this document is attributed to — never shown as a citation source unless it matches reality (see authority field).', max_length=160)),
                ('authority', models.CharField(choices=[('OFFICIAL', 'Official published guidance from the named organization'), ('REFERENCE', 'General reference material — not verbatim official text'), ('INTERNAL', "GramSentinel's own application documentation")], max_length=16)),
                ('document_type', models.CharField(choices=[('GUIDELINE', 'Clinical guideline'), ('SURVEILLANCE_GUIDANCE', 'Surveillance guidance'), ('CHW_GUIDANCE', 'CHW / ASHA guidance'), ('REFERRAL_GUIDANCE', 'Referral guidance'), ('TERMINOLOGY_REFERENCE', 'Terminology reference'), ('INVESTIGATION_GUIDANCE', 'Investigation guidance'), ('APPLICATION_DOCUMENTATION', 'Application documentation')], max_length=32)),
                ('topic', models.CharField(choices=[('CLINICAL', 'Clinical guidance'), ('PUBLIC_HEALTH', 'Public health'), ('SURVEILLANCE', 'Surveillance'), ('CHW_ASHA', 'CHW / ASHA guidance'), ('REFERRAL', 'Referral guidance'), ('TERMINOLOGY', 'Terminology reference'), ('INVESTIGATION', 'Investigation guidance'), ('GRAMSENTINEL_INTERNAL', 'GramSentinel application documentation')], max_length=32)),
                ('subtopic', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('version', models.CharField(default='1', max_length=32)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=120)),
                ('license_note', models.CharField(blank=True, default='', max_length=200)),
                ('checksum', models.CharField(editable=False, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='knowledge.knowledgedocument')),
            ],
            options={
                'ordering': ['organization', 'title', '-version'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('section_title', models.CharField(blank=True, default='', max_length=200)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=64)),
                ('embedding_dim', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='RagQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=32)),
                ('user_role', models.CharField(blank=True, max_length=32)),
                ('topic', models.CharField(blank=True, max_length=32)),
                ('retrieved_document_ids', models.JSONField(default=list)),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
                ('grounded', models.BooleanField(default=False, help_text='True if relevance cleared RAG_MIN_RELEVANCE.')),
                ('used_llm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['topic', 'document_type', 'active'], name='knowledge_k_topic_1f8ac1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
