# Generated by Django 5.0.6 on 2026-08-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('API', 'Authorised API'), ('EXPORT', 'Approved aggregated export'), ('PORTAL', 'Reporting portal / mobile form'), ('PUBLIC_FEED', 'Public machine-readable feed'), ('INTERNAL', 'Computed internally by GramSentinel')], max_length=16)),
                ('week_label', models.CharField(blank=True, max_length=16)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_accepted', models.PositiveIntegerField(default=0)),
                ('records_rejected', models.PositiveIntegerField(default=0)),
                ('records_deduplicated', models.PositiveIntegerField(default=0)),
                ('missing_flagged', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected in validation'), ('PARTIAL', 'Accepted with flags')], default='ACCEPTED', max_length=16)),
                ('validation_notes', models.JSONField(blank=True, default=list)),
                ('simulated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_events', to='community.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
