# Generated by Django 5.0.6 on 2026-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(default=list, help_text='Normalised symptom codes.')),
                ('raw_symptom_text', models.TextField(blank=True)),
                ('duration_days', models.PositiveSmallIntegerField(default=0)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('primary_category', models.CharField(choices=[('FEVER', 'Fever-related'), ('RESPIRATORY', 'Respiratory'), ('DIARRHOEAL', 'Diarrhoeal'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation'), ('OTHER', 'Other')], default='OTHER', help_text='Drives which aggregated community signal this contributes to.', max_length=24)),
                ('triage_level', models.CharField(choices=[('ROUTINE', 'Routine'), ('CONCERNING', 'Concerning'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=16)),
                ('triage_score', models.FloatField(default=0.0)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('referral_recommendation', models.TextField(blank=True)),
                ('followup_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('escalation_forced', models.BooleanField(default=False, help_text='True when the deterministic red-flag rule set overrode the model.')),
                ('safety_status', models.CharField(blank=True, max_length=48)),
                ('agent_trace', models.JSONField(blank=True, default=list, help_text="Ordered record of each agent's input summary and output.")),
                ('llm_used', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False, help_text='True for a preview run that the worker has not submitted yet.')),
                ('aggregated_at', models.DateTimeField(blank=True, help_text='When this encounter was folded into an anonymised community signal.', null=True)),
                ('encounter_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
