# Generated by Django 5.0.6 on 2026-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_patientassessment_primary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientassessment',
            name='other_symptom_text',
            field=models.TextField(blank=True, default='', help_text="The worker's own words for a symptom the predefined list does not cover. Optional; blank on assessments recorded without it. Stored as supplementary context — it is not interpreted by the triage rules or the deterministic safety checks."),
        ),
        migrations.AddField(
            model_name='patientassessment',
            name='symptom_timeline',
            field=models.JSONField(blank=True, default=list, help_text="Optional day-wise symptom history: [{'day': 1, 'detail': '...'}]. Empty for assessments recorded without it. Supplementary context only; duration_days above remains the recorded duration."),
        ),
    ]
