# Generated by Django 5.0.6 on 2026-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_patientassessment_other_symptom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientassessment',
            name='sugar_mg_dl',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blood glucose reading in mg/dL, if recorded. Not used by triage logic.', null=True),
        ),
    ]
