# Generated by Django 5.0.6 on 2026-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_patientassessment_sugar_mg_dl'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientassessment',
            name='blood_sugar_measurement_type',
            field=models.CharField(blank=True, choices=[('fasting', 'Fasting'), ('random', 'Random'), ('2_hour_post_meal', '2-hour post-meal')], default='', help_text='Context for sugar_mg_dl (fasting/random/2-hour post-meal). Blank on assessments with no sugar reading, and on assessments recorded before this field existed. Not used by triage logic.', max_length=24),
        ),
    ]
