# Generated by Django 5.0.6 on 2026-09-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_patientassessment_blood_sugar_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Defaults to NORMAL for every pre-existing follow-up (auto-scheduled or worker-created). Set explicitly when a Health Officer requests a follow-up, e.g. from Pregnancy Follow-up.', max_length=16),
        ),
    ]
