# Generated by Django 5.0.6 on 2026-09-15 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0007_sourceoperationalcontext'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_village_area_hectares_village_asha_chw_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('record_label', models.CharField(help_text="Plain-language identifier, e.g. 'Assessment #1024' — never a patient name.", max_length=120)),
                ('original_snapshot', models.JSONField(default=dict, help_text='Plain-language field/value pairs as they stood when this request was made.')),
                ('mistake_description', models.TextField(max_length=4000)),
                ('proposed_correction', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RETURNED_FOR_CORRECTION', 'Returned for correction'), ('RESUBMITTED', 'Resubmitted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=32)),
                ('supervisor_comment', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, help_text="Set when an APPROVED correction's effect (see services.apply_correction_effect) has been carried out.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.village')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RETURNED_FOR_CORRECTION', 'Returned for correction'), ('RESUBMITTED', 'Resubmitted'), ('REJECTED', 'Rejected')], max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspace.correctionrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RETURNED_FOR_CORRECTION', 'Returned for correction'), ('RESUBMITTED', 'Resubmitted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=32)),
                ('supervisor_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='community.communityreport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.village')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('RETURNED_FOR_CORRECTION', 'Returned for correction'), ('RESUBMITTED', 'Resubmitted'), ('REJECTED', 'Rejected')], max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspace.reportapproval')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(max_length=8000)),
                ('attachment', models.TextField(blank=True, default='')),
                ('attachment_filename', models.CharField(blank=True, default='', max_length=200)),
                ('attachment_mime', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.village')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='correctionrequest',
            index=models.Index(fields=['village', 'status'], name='workspace_c_village_d58726_idx'),
        ),
        migrations.AddIndex(
            model_name='correctionrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='workspace_c_content_c4397d_idx'),
        ),
        migrations.AddIndex(
            model_name='reportapproval',
            index=models.Index(fields=['village', 'status'], name='workspace_r_village_e161a2_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisormessage',
            index=models.Index(fields=['worker', 'created_at'], name='workspace_s_worker__1fc09f_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisormessage',
            index=models.Index(fields=['officer', 'created_at'], name='workspace_s_officer_410614_idx'),
        ),
    ]
