# Generated by Django 5.0.6 on 2026-09-15 14:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_village_area_hectares_village_asha_chw_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_finding', models.TextField()),
                ('source_type', models.CharField(choices=[('FIELD_VISIT', 'Field visit'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other operational issue')], default='OTHER', max_length=16)),
                ('deadline', models.DateField()),
                ('required_resources', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=16)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans', to='core.village')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_plans', to='fieldops.department')),
            ],
            options={
                'ordering': ['deadline', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlanProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_percentage', models.PositiveSmallIntegerField()),
                ('new_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('update_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='fieldops.actionplan')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DRINKING_WATER_SANITATION', 'Drinking Water & Sanitation'), ('SCHOOL_ANGANWADI', 'School & Anganwadi'), ('PUBLIC_PLACE_HYGIENE', 'Public-Place Hygiene'), ('WASTE_MANAGEMENT', 'Waste Management')], max_length=32)),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='fieldops_ch_categor_90ba79_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('objective', models.CharField(max_length=300)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=16)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('outcome_summary', models.TextField(blank=True, default='')),
                ('observations', models.TextField(blank=True, default='')),
                ('issues_identified', models.TextField(blank=True, default='')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_visits', to='core.village')),
            ],
            options={
                'ordering': ['-visit_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='source_field_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='fieldops.fieldvisit'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('DRINKING_WATER_SANITATION', 'Drinking Water & Sanitation'), ('SCHOOL_ANGANWADI', 'School & Anganwadi'), ('PUBLIC_PLACE_HYGIENE', 'Public-Place Hygiene'), ('WASTE_MANAGEMENT', 'Waste Management')], max_length=32)),
                ('inspection_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=16)),
                ('summary_remarks', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='core.village')),
            ],
            options={
                'ordering': ['-inspection_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='source_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='fieldops.inspection'),
        ),
        migrations.CreateModel(
            name='InspectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('filename', models.CharField(blank=True, default='', max_length=200)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fieldops.inspection')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('NEEDS_ACTION', 'Needs action')], max_length=16, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='fieldops.inspection')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fieldops.checklistitemtemplate')),
            ],
            options={
                'ordering': ['template_item__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='source_checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='fieldops.inspectionchecklistresponse'),
        ),
        migrations.AddIndex(
            model_name='fieldvisit',
            index=models.Index(fields=['village', 'status'], name='fieldops_fi_village_14ebb9_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvisit',
            index=models.Index(fields=['visit_date'], name='fieldops_fi_visit_d_d15d63_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvisit',
            index=models.Index(fields=['assigned_officer'], name='fieldops_fi_assigne_637153_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['village', 'status'], name='fieldops_in_village_ab5b25_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspection_type'], name='fieldops_in_inspect_07e61b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionchecklistresponse',
            unique_together={('inspection', 'template_item')},
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['village', 'status'], name='fieldops_ac_village_1f4bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['deadline'], name='fieldops_ac_deadlin_72f366_idx'),
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['department'], name='fieldops_ac_departm_71553e_idx'),
        ),
    ]
