# Generated by Django 5.0.6 on 2026-08-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FEVER', 'Fever-related'), ('RESPIRATORY', 'Respiratory'), ('DIARRHOEAL', 'Diarrhoeal'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation'), ('OTHER', 'Other')], max_length=24)),
                ('week_label', models.CharField(max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('baseline', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_reported', models.BooleanField(default=True)),
                ('data_quality', models.CharField(choices=[('GOOD', 'Good'), ('PARTIAL', 'Partial'), ('POOR', 'Poor'), ('MISSING', 'Not submitted')], default='GOOD', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start', 'source__kind'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('CHW', 'Community Health Worker reports'), ('PHC', 'PHC aggregate trends'), ('PHARMACY', 'Pharmacy category trends'), ('SCHOOL', 'School absenteeism'), ('WEATHER', 'Weather / environment'), ('LAB', 'Laboratory evidence'), ('RURALCARE_AGGREGATE', 'Aggregated RuralCare signal')], max_length=32)),
                ('channel', models.CharField(choices=[('API', 'Authorised API'), ('EXPORT', 'Approved aggregated export'), ('PORTAL', 'Reporting portal / mobile form'), ('PUBLIC_FEED', 'Public machine-readable feed'), ('INTERNAL', 'Computed internally by GramSentinel')], default='PORTAL', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('simulated', models.BooleanField(default=True, help_text='True for the whole prototype. No real institutional feed exists.')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(help_text='e.g. 2026-W32', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('fever_cases', models.PositiveIntegerField(default=0)),
                ('respiratory_cases', models.PositiveIntegerField(default=0)),
                ('diarrhoeal_cases', models.PositiveIntegerField(default=0)),
                ('other_cases', models.PositiveIntegerField(default=0)),
                ('unusual_observation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_reports', to='core.village')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
    ]
