# Generated by Django 5.0.6 on 2026-08-12 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitysignal',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='core.village'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='core.facility'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.village'),
        ),
        migrations.AddField(
            model_name='communitysignal',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='community.datasource'),
        ),
        migrations.AlterUniqueTogether(
            name='communityreport',
            unique_together={('village', 'week_label', 'worker')},
        ),
        migrations.AddIndex(
            model_name='communitysignal',
            index=models.Index(fields=['village', 'week_label', 'category'], name='community_c_village_730ec4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitysignal',
            unique_together={('source', 'category', 'week_label')},
        ),
    ]
