# Generated by Django 5.0.6 on 2026-08-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Set when a health officer has opened this report.', null=True),
        ),
        migrations.AlterField(
            model_name='communitysignal',
            name='category',
            field=models.CharField(choices=[('FEVER', 'Fever / febrile illness'), ('RESPIRATORY', 'Respiratory illness'), ('DIARRHOEAL', 'Diarrhoeal / gastrointestinal illness'), ('SKIN', 'Skin conditions / infections'), ('EYE', 'Eye-related conditions'), ('VECTOR_BORNE', 'Vector-borne illness indicators'), ('MOSQUITO_BORNE', 'Mosquito-borne illness indicators'), ('WATER_BORNE', 'Water-borne illness indicators'), ('FOOD_BORNE', 'Food-borne illness indicators'), ('ANIMAL_BITE', 'Animal / insect bite incidents'), ('POISONING', 'Suspected poisoning'), ('INJURY', 'Injuries / accidents'), ('MATERNAL', 'Maternal health concerns'), ('CHILD_HEALTH', 'Child health concerns'), ('MALNUTRITION', 'Malnutrition-related concerns'), ('DEHYDRATION', 'Dehydration'), ('HEAT_RELATED', 'Heat-related illness'), ('MENTAL_HEALTH', 'Mental health concerns'), ('OTHER_COMMUNICABLE', 'Other communicable illness indicators'), ('OTHER_NON_COMMUNICABLE', 'Other non-communicable health concerns'), ('OTHER', 'Other (describe below)'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation')], max_length=32),
        ),
        migrations.CreateModel(
            name='CommunityReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FEVER', 'Fever / febrile illness'), ('RESPIRATORY', 'Respiratory illness'), ('DIARRHOEAL', 'Diarrhoeal / gastrointestinal illness'), ('SKIN', 'Skin conditions / infections'), ('EYE', 'Eye-related conditions'), ('VECTOR_BORNE', 'Vector-borne illness indicators'), ('MOSQUITO_BORNE', 'Mosquito-borne illness indicators'), ('WATER_BORNE', 'Water-borne illness indicators'), ('FOOD_BORNE', 'Food-borne illness indicators'), ('ANIMAL_BITE', 'Animal / insect bite incidents'), ('POISONING', 'Suspected poisoning'), ('INJURY', 'Injuries / accidents'), ('MATERNAL', 'Maternal health concerns'), ('CHILD_HEALTH', 'Child health concerns'), ('MALNUTRITION', 'Malnutrition-related concerns'), ('DEHYDRATION', 'Dehydration'), ('HEAT_RELATED', 'Heat-related illness'), ('MENTAL_HEALTH', 'Mental health concerns'), ('OTHER_COMMUNICABLE', 'Other communicable illness indicators'), ('OTHER_NON_COMMUNICABLE', 'Other non-communicable health concerns'), ('OTHER', 'Other (describe below)'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation')], max_length=32)),
                ('case_count', models.PositiveIntegerField(default=0, help_text='Reported/observed cases. Not confirmed diagnoses.')),
                ('description', models.TextField(blank=True, help_text="What the worker observed. Required for 'Other' categories.")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='community.communityreport')),
            ],
            options={
                'verbose_name_plural': 'community report entries',
                'ordering': ['category', 'id'],
            },
        ),
    ]
