# Generated by Django 5.0.6 on 2026-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communityreport_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreportentry',
            name='category',
            field=models.CharField(choices=[('FEVER', 'Fever / febrile illness'), ('RESPIRATORY', 'Respiratory illness'), ('DIARRHOEAL', 'Diarrhoeal / gastrointestinal illness'), ('SKIN', 'Skin conditions / infections'), ('EYE', 'Eye-related conditions'), ('VECTOR_BORNE', 'Vector-borne illness indicators'), ('MOSQUITO_BORNE', 'Mosquito-borne illness indicators'), ('WATER_BORNE', 'Water-borne illness indicators'), ('FOOD_BORNE', 'Food-borne illness indicators'), ('ANIMAL_BITE', 'Animal / insect bite incidents'), ('POISONING', 'Suspected poisoning'), ('INJURY', 'Injuries / accidents'), ('MATERNAL', 'Maternal health concerns'), ('CHILD_HEALTH', 'Child health concerns'), ('MALNUTRITION', 'Malnutrition-related concerns'), ('DEHYDRATION', 'Dehydration'), ('HEAT_RELATED', 'Heat-related illness'), ('MENTAL_HEALTH', 'Mental health concerns'), ('OTHER_COMMUNICABLE', 'Other communicable illness indicators'), ('OTHER_NON_COMMUNICABLE', 'Other non-communicable health concerns'), ('OTHER', 'Other health concern'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation')], max_length=32),
        ),
        migrations.AlterField(
            model_name='communitysignal',
            name='category',
            field=models.CharField(choices=[('FEVER', 'Fever / febrile illness'), ('RESPIRATORY', 'Respiratory illness'), ('DIARRHOEAL', 'Diarrhoeal / gastrointestinal illness'), ('SKIN', 'Skin conditions / infections'), ('EYE', 'Eye-related conditions'), ('VECTOR_BORNE', 'Vector-borne illness indicators'), ('MOSQUITO_BORNE', 'Mosquito-borne illness indicators'), ('WATER_BORNE', 'Water-borne illness indicators'), ('FOOD_BORNE', 'Food-borne illness indicators'), ('ANIMAL_BITE', 'Animal / insect bite incidents'), ('POISONING', 'Suspected poisoning'), ('INJURY', 'Injuries / accidents'), ('MATERNAL', 'Maternal health concerns'), ('CHILD_HEALTH', 'Child health concerns'), ('MALNUTRITION', 'Malnutrition-related concerns'), ('DEHYDRATION', 'Dehydration'), ('HEAT_RELATED', 'Heat-related illness'), ('MENTAL_HEALTH', 'Mental health concerns'), ('OTHER_COMMUNICABLE', 'Other communicable illness indicators'), ('OTHER_NON_COMMUNICABLE', 'Other non-communicable health concerns'), ('OTHER', 'Other health concern'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation')], max_length=32),
        ),
    ]
