# Generated by Django 5.0.6 on 2026-09-14 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_communityreportentry_category_and_more'),
        ('core', '0002_village_area_hectares_village_asha_chw_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSignalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FEVER', 'Fever / febrile illness'), ('RESPIRATORY', 'Respiratory illness'), ('DIARRHOEAL', 'Diarrhoeal / gastrointestinal illness'), ('SKIN', 'Skin conditions / infections'), ('EYE', 'Eye-related conditions'), ('VECTOR_BORNE', 'Vector-borne illness indicators'), ('MOSQUITO_BORNE', 'Mosquito-borne illness indicators'), ('WATER_BORNE', 'Water-borne illness indicators'), ('FOOD_BORNE', 'Food-borne illness indicators'), ('ANIMAL_BITE', 'Animal / insect bite incidents'), ('POISONING', 'Suspected poisoning'), ('INJURY', 'Injuries / accidents'), ('MATERNAL', 'Maternal health concerns'), ('CHILD_HEALTH', 'Child health concerns'), ('MALNUTRITION', 'Malnutrition-related concerns'), ('DEHYDRATION', 'Dehydration'), ('HEAT_RELATED', 'Heat-related illness'), ('MENTAL_HEALTH', 'Mental health concerns'), ('OTHER_COMMUNICABLE', 'Other communicable illness indicators'), ('OTHER_NON_COMMUNICABLE', 'Other non-communicable health concerns'), ('OTHER', 'Other health concern'), ('ENVIRONMENT', 'Environmental'), ('LAB_CONFIRMATION', 'Laboratory confirmation')], max_length=32)),
                ('source_kind', models.CharField(choices=[('CHW', 'Community Health Worker reports'), ('PHC', 'PHC aggregate trends'), ('PHARMACY', 'Pharmacy category trends'), ('SCHOOL', 'School absenteeism'), ('WEATHER', 'Weather / environment'), ('LAB', 'Laboratory evidence'), ('RURALCARE_AGGREGATE', 'Aggregated RuralCare signal')], max_length=32)),
                ('week_label', models.CharField(max_length=16)),
                ('baseline', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Set when a health officer has opened this report.', null=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_reports', to='community.communitysignal')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_signal_reports', to='core.village')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_signal_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['village', '-created_at'], name='community_l_village_39700e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='localsignalreport',
            constraint=models.UniqueConstraint(fields=('worker', 'signal'), name='unique_local_signal_report_per_worker_signal'),
        ),
    ]
