# Generated by Django 5.0.6 on 2026-09-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_communityreportentry_category_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='captured_offline',
            field=models.BooleanField(default=False, help_text='True when this report was recorded on a device with no connectivity.'),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='client_created_at',
            field=models.DateTimeField(blank=True, help_text="When the worker completed the report on their device. Device clock, so it is displayed as the worker's own record of when they observed this — never used for ordering against server times.", null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_report_at',
            field=models.DateTimeField(blank=True, help_text='When this source last successfully delivered data, set by the Integration Layer on every accepted record. Null means nothing has ever been received — which is not the same as a zero reading.', null=True),
        ),
        migrations.CreateModel(
            name='OfflineSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_report_uid', models.UUIDField(help_text='Generated on the device when the report was saved, before any sync.', unique=True)),
                ('client_created_at', models.DateTimeField(help_text='Device clock — when the worker completed the report offline.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0, help_text='How many duplicate deliveries of this report the server absorbed.')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_submissions', to='community.communityreport')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_submissions', to='core.village')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
