# Generated by Django 5.0.6 on 2026-09-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_localsignalreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='client_created_at',
            field=models.DateTimeField(blank=True, help_text='When the worker actually filled this report in, if it was queued on the device before syncing. Never overwritten by the sync time — `submitted_at` above is when the server received it, which can be well after this.', null=True),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text="Client-generated key so an offline retry (timeout, dropped connection, duplicate tap) can never create a second report. `null` (not '') for rows with no key, so multiple online submissions can coexist under one UNIQUE constraint — NULL is not compared equal to NULL in SQL, unlike two empty strings would be.", max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='communityreport',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text="The server's own authoritative receipt time. This IS the 'server_received_at' concept for offline sync — a separate, identically-timed column was not added, to avoid storing the same moment twice."),
        ),
    ]
