# Generated by Django 5.0.6 on 2026-09-15 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_communityreport_client_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOperationalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('TEMPORARILY_UNAVAILABLE', 'Temporarily unavailable'), ('EXPECTED_VARIATION', 'Expected unusual activity')], max_length=32)),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_contexts', to='community.datasource')),
            ],
            options={
                'ordering': ['-starts_on'],
                'indexes': [models.Index(fields=['source', 'starts_on', 'ends_on'], name='community_s_source__9340b4_idx')],
            },
        ),
    ]
