# Generated by Django 5.0.6 on 2026-09-16 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_sourceoperationalcontext'),
        ('core', '0002_village_area_hectares_village_asha_chw_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='report_type',
            field=models.CharField(choices=[('GENERAL', 'General community health'), ('PREGNANCY', 'Pregnancy follow-up')], default='GENERAL', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='communityreport',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'GENERAL')), fields=('village', 'week_label', 'worker'), name='unique_general_report_per_worker_week'),
        ),
    ]
