# Generated by Django 5.0.6 on 2026-09-15 22:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_village_area_hectares_village_asha_chw_status_and_more'),
        ('patients', '0004_patient_height_cm_patient_house_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picme_rch_id', models.CharField(blank=True, default='', help_text='The PICME/RCH ID already provided to the citizen through the appropriate government registration process. Never generated by this system.', max_length=64)),
                ('picme_rch_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REGISTRATION_PENDING', 'Registration Pending'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=24)),
                ('lmp', models.DateField(blank=True, help_text='Last menstrual period, if known.', null=True)),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Only stored if already known from an existing clinical record. This system does not calculate or guess an EDD.', null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.localdate)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TRANSFERRED', 'Transferred'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_health_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pregnancies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_profiles', to='patients.patient')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancy_profiles', to='core.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyProfileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROFILE_CREATED', 'Pregnancy profile created'), ('PICME_UPDATED', 'PICME/RCH ID updated'), ('VISIT_RECORDED', 'Pregnancy visit recorded'), ('NEXT_CHECKUP_CHANGED', 'Next check-up date changed'), ('STATUS_CHANGED', 'Pregnancy status changed'), ('FOLLOWUP_TASK_CREATED', 'Health worker follow-up requested')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pregnancy_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pregnancy.pregnancyprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyVisitAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveSmallIntegerField(choices=[(1, 'Visit 1 - First Pregnancy Visit'), (2, 'Visit 2 - Follow-up ANC Visit'), (3, 'Visit 3 - Baby Movement / Risk Check'), (4, 'Visit 4 - Delivery Preparation')])),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('questionnaire_responses', models.JSONField(blank=True, default=dict, help_text="{question_key: 'YES'/'NO'/'UNKNOWN'}, keys fixed per visit_number.")),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('warning_signs', models.JSONField(blank=True, default=list, help_text='Question keys answered YES to a warning-sign question.')),
                ('rule_flags', models.JSONField(blank=True, default=list)),
                ('ai_guidance', models.JSONField(blank=True, default=dict)),
                ('llm_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pregnancy_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='pregnancy.pregnancyprofile')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancy_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['visit_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pregnancyprofile',
            index=models.Index(fields=['village', 'status'], name='pregnancy_p_village_ab2e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancyprofile',
            index=models.Index(fields=['patient', 'status'], name='pregnancy_p_patient_3527b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancyprofile',
            index=models.Index(fields=['next_checkup_date'], name='pregnancy_p_next_ch_463780_idx'),
        ),
        migrations.AddConstraint(
            model_name='pregnancyprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('patient',), name='unique_active_pregnancy_per_patient'),
        ),
        migrations.AddIndex(
            model_name='pregnancyprofileevent',
            index=models.Index(fields=['pregnancy_profile', 'created_at'], name='pregnancy_p_pregnan_413bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancyvisitassessment',
            index=models.Index(fields=['pregnancy_profile', 'visit_number'], name='pregnancy_p_pregnan_3f85ff_idx'),
        ),
    ]
