# Generated by Django 5.0.6 on 2026-09-16 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_communityreport_unique_together_and_more'),
        ('pregnancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancyprofileevent',
            name='event_type',
            field=models.CharField(choices=[('PROFILE_CREATED', 'Pregnancy profile created'), ('PICME_UPDATED', 'PICME/RCH ID updated'), ('VISIT_RECORDED', 'Pregnancy visit recorded'), ('NEXT_CHECKUP_CHANGED', 'Next check-up date changed'), ('STATUS_CHANGED', 'Pregnancy status changed'), ('FOLLOWUP_TASK_CREATED', 'Health worker follow-up requested'), ('COMMUNITY_REPORT_SUBMITTED', 'Pregnancy community report submitted')], max_length=32),
        ),
        migrations.CreateModel(
            name='PregnancyCommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_visit_count', models.PositiveSmallIntegerField(default=0)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False, help_text="Derived from pregnancy.rules.evaluate_profile_rules at submission time (FOLLOW_UP_OVERDUE / URGENT_CLINICAL_REVIEW) — never a worker's own free-text judgement.")),
                ('reason', models.TextField(help_text='Why this report is being raised.')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_detail', to='community.communityreport')),
                ('pregnancy_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to='pregnancy.pregnancyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
