# Generated by Django 5.0.6 on 2026-09-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_experience_years_user_phone_number_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CHW_PHC_WORKER', 'CHW / PHC Worker'), ('HEALTH_OFFICER', 'Health Officer'), ('ADMIN', 'Administrator')], default='CHW_PHC_WORKER', max_length=32),
        ),
    ]
