# Generated by Django 5.0.6 on 2026-08-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('cluster', models.CharField(help_text='Geographic cluster used for corroboration (Safety Engine R3).', max_length=120)),
                ('block', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('PHC', 'Primary Health Centre'), ('SUB_CENTRE', 'Sub-centre'), ('PHARMACY', 'Pharmacy'), ('SCHOOL', 'School'), ('LAB', 'Laboratory')], max_length=24)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.village')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
    ]
