# Generated by Django 5.0.6 on 2026-09-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='area_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='asha_chw_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='village',
            name='census_village_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='village',
            name='chc_inside_village_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='village',
            name='children_0_6',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='demographic_baseline_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='e.g. 2011 for a Census 2011 baseline. Population/households/male/female/children figures above are as of this year — never presented as a current estimate.', null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='female_population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='health_sub_centre_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='village',
            name='households',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='male_population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='nearby_government_phc_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='village',
            name='phc_inside_village_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='village',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='village',
            name='real_world_profile',
            field=models.BooleanField(default=False, help_text='True only for a village whose demographic/geographic profile below has been populated from real-world research, never inferred or guessed.'),
        ),
        migrations.AddField(
            model_name='village',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='village',
            name='taluk',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
