# Generated by Django 5.0.6 on 2026-09-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('scenario_type', models.CharField(choices=[('EMERGING_SIGNAL', 'Emerging Community Signal'), ('STABLE_COMMUNITY', 'Stable Community'), ('WEAK_EVIDENCE', 'False Positive / Weak Evidence'), ('MISSING_DATA', 'Missing Data'), ('SOURCE_DISAGREEMENT', 'Source Disagreement'), ('WHAT_IF', 'What-If Simulation'), ('REPLAY', 'Signal Replay'), ('LIVE_EMERGENCE', 'Live Signal Emergence')], max_length=32)),
                ('description', models.TextField(help_text='Plain-language description shown on the scenario card.')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
            ],
            options={
                'ordering': ['village__code', 'scenario_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=16)),
                ('replay_position', models.PositiveSmallIntegerField(default=0, help_text='Which week the replay/advance cursor is on. Unused until Phase 3/7.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_officer', models.ForeignKey(blank=True, help_text='Null for a seed-created template session (Phase 2). Set to the initiating officer from Phase 3 onward.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simulation.simulationscenario')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(blank=True, max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_strength', models.FloatField(blank=True, null=True)),
                ('investigation_priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='', max_length=16)),
                ('is_what_if', models.BooleanField(default=False, help_text='True for a hypothetical (Phase 7 What-If) result rather than a straightforward scenario run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['session', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_notes', models.TextField(blank=True, default='')),
                ('decision', models.CharField(blank=True, choices=[('VALID_SIGNAL', 'Valid signal'), ('FALSE_ALERT', 'False alert'), ('RESOLVED', 'Resolved')], default='', max_length=24)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('is_simulation', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['session', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('source_signals', models.JSONField(blank=True, default=dict, help_text='Denormalized weekly category summary — see model docstring for the JSON contract. Not the source of truth for missing-vs-zero; see SimulationSourceSignal for that.')),
                ('is_synthetic', models.BooleanField(default=True, help_text='Always True for a seeded scenario. Exists as a real field (not assumed) because a future Replay scenario (Phase 7) may carry genuine historical data through the same schema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['session', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='SimulationAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'OK'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['session', 'started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSourceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('CHW', 'Community Health Worker reports'), ('PHC', 'PHC aggregate trends'), ('PHARMACY', 'Pharmacy category trends'), ('SCHOOL', 'School absenteeism'), ('WEATHER', 'Weather / environment'), ('LAB', 'Laboratory evidence'), ('RURALCARE_AGGREGATE', 'Aggregated RuralCare signal')], max_length=32)),
                ('value', models.FloatField(blank=True, help_text='Null when reported=False. Never coerced to 0 for a missing report.', null=True)),
                ('reported', models.BooleanField(default=True, help_text='False means no report was received this week for this source — structurally distinct from a genuine 0.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_source_signals', to='simulation.simulationevent')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
            ],
            options={
                'ordering': ['event', 'source_type'],
            },
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['village', 'scenario_type'], name='simulation__village_d1448e_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationscenario',
            index=models.Index(fields=['is_active'], name='simulation__is_acti_e88ffe_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationscenario',
            constraint=models.UniqueConstraint(fields=('village', 'scenario_type', 'version'), name='unique_simulation_scenario_version_per_village'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['village'], name='simulation__village_a059a1_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['status'], name='simulation__status_832b82_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsession',
            index=models.Index(fields=['scenario'], name='simulation__scenari_927edf_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsafetycheck',
            index=models.Index(fields=['session'], name='simulation__session_a36036_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['session'], name='simulation__session_1c3b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationinvestigation',
            index=models.Index(fields=['session'], name='simulation__session_76adc9_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['session', 'week_number'], name='simulation__session_00ad27_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationevent',
            constraint=models.UniqueConstraint(fields=('session', 'week_number'), name='unique_simulation_event_week_per_session'),
        ),
        migrations.AddIndex(
            model_name='simulationagentrun',
            index=models.Index(fields=['session'], name='simulation__session_9015de_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationagentrun',
            index=models.Index(fields=['status'], name='simulation__status_4e0fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationsourcesignal',
            index=models.Index(fields=['event', 'source_type'], name='simulation__event_i_779794_idx'),
        ),
        migrations.AddConstraint(
            model_name='simulationsourcesignal',
            constraint=models.UniqueConstraint(fields=('event', 'source_type'), name='unique_simulation_source_signal_per_event'),
        ),
        migrations.AddConstraint(
            model_name='simulationsourcesignal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reported', True), ('value__isnull', False)), models.Q(('reported', False), ('value__isnull', True)), _connector='OR'), name='simulation_source_signal_missing_is_not_zero'),
        ),
    ]
