# Generated by Django 5.0.6 on 2026-09-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationagentrun',
            name='duration_ms',
            field=models.FloatField(blank=True, help_text='Null for a stage that has not run (WAITING) or could not be timed.', null=True),
        ),
        migrations.AlterField(
            model_name='simulationagentrun',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='WAITING', max_length=16),
        ),
    ]
