# Generated by Django 5.0.6 on 2026-09-13 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('simulation', '0003_simulationresult_gate_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationinvestigation',
            name='activity_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='simulationinvestigation',
            name='checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='simulationinvestigation',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_investigation_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulationinvestigation',
            name='decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulationinvestigation',
            name='observations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='simulationinvestigation',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('READY_FOR_DECISION', 'Ready for decision'), ('DECISION_RECORDED', 'Decision recorded'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=24),
        ),
        migrations.AddField(
            model_name='simulationinvestigation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='simulationinvestigation',
            name='decision',
            field=models.CharField(blank=True, choices=[('CONTINUE_MONITORING', 'Continue monitoring'), ('REQUEST_MORE_DATA', 'Request more data'), ('VERIFY_WITH_PHC', 'Verify with PHC'), ('CONDUCT_FIELD_VERIFICATION', 'Conduct field verification'), ('REQUEST_LABORATORY_VERIFICATION', 'Request laboratory verification'), ('ESCALATE_FOR_HUMAN_REVIEW', 'Escalate for human review'), ('CLOSE_AS_INSUFFICIENT_EVIDENCE', 'Close as insufficient evidence')], default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='simulationinvestigation',
            constraint=models.UniqueConstraint(fields=('session',), name='unique_simulation_investigation_per_session'),
        ),
    ]
