# Generated by Django 5.0.6 on 2026-09-13 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('simulation', '0004_simulationinvestigation_activity_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness', models.CharField(blank=True, choices=[('VERY_USEFUL', 'Very useful'), ('USEFUL', 'Useful'), ('PARTIALLY_USEFUL', 'Partially useful'), ('NOT_USEFUL', 'Not useful')], default='', max_length=24)),
                ('evidence_sufficiency', models.CharField(blank=True, choices=[('SUFFICIENT', 'Sufficient'), ('PARTIALLY_SUFFICIENT', 'Partially sufficient'), ('INSUFFICIENT', 'Insufficient')], default='', max_length=24)),
                ('recommendation_helpful', models.CharField(blank=True, choices=[('YES', 'Yes'), ('PARTIALLY', 'Partially'), ('NO', 'No')], default='', max_length=16)),
                ('additional_verification_required', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='', max_length=8)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_simulation', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='simulation.simulationinvestigation')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_feedback_entries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='simulation.simulationsession')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.village')),
            ],
            options={
                'ordering': ['investigation', '-created_at'],
                'indexes': [models.Index(fields=['session'], name='simulation__session_975d77_idx'), models.Index(fields=['investigation'], name='simulation__investi_689c1d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='simulationfeedback',
            constraint=models.UniqueConstraint(fields=('investigation',), name='unique_simulation_feedback_per_investigation'),
        ),
    ]
